### PR TITLE
[WIP] Albert

### PR DESCRIPTION
**Pull request by tejasvaidhyadev**
Hi everyone
I am adding **ALBERT [WIP]** 
Currently only raw code is given in PR.
Dependencies - **Transformers.jl , WordTokenizer.jl**

I am not exporting any function.I am still in middle of deciding what is the best way to use it.
But i am adding some important codes which is used for conversion of pretrained checkpoints and in Demo file below
### Roadmap
- [x] SentencePiece - containing wordpiece as well as unigram model(python Wrapper (for now) as well as julia implementation (under development)) 
- [X] tfckpt2bsonforalbert.jl - for conversion of Tensorflow checkpoint to BSON weights
- [x] albert transformer - It is not completed but is based on transformers.jl transformer
- [X] model file - for now is kept inside ALBERT folder but it just the general wrapping structure to load ALBERT pretrain weight
- [x]  APIs - alberttokenizer , albertmasklm , albertforsequenceclassification etc. 
- [x] our own hosted Pretrain model manage by datadeps.jl
- [x] Documentation, test and Tutorial
- [x] code and APIs for fine tuning and Data loading 
apart from above  refactoring and cleaning of code is remaining

### Important links

Pretrained weights [link](https://drive.google.com/drive/folders/1HHTlS_jBYRE4cG0elITEH7fAkiNmrEgz?usp=sharing) .

- The pretrained weigths are converted from tensorflow check point released by google-research.
- The code for conversion is given in `tfckpt2bsonforalbert.jl`
- Currently Pretrained weight for Version-1 is given soon I will release it for version-2

For detail refer - [link](https://github.com/tejasvaidhyadev/ALBERT.jl)

Demo - [link](https://github.com/tejasvaidhyadev/ALBERT.jl/blob/master/docs/Demo.ipynb)

**PS**
All the suggestions are welcome

### CODE REVIEW

**Comment by tejasvaidhyadev** [comment]
Sorry for closing PR before
Commit history of git is now updated

**Comment by tejasvaidhyadev** [comment]
## Pretrained weights 
Version 2 of ALBERT converted Bson is released
- [base](https://drive.google.com/drive/u/1/folders/1DlX_WZacsjt6O8EDaawKJ-x4RWP46Xj-)
- [large](https://drive.google.com/drive/u/1/folders/1DlX_WZacsjt6O8EDaawKJ-x4RWP46Xj-)
- [xlarge](https://drive.google.com/drive/u/1/folders/1DlX_WZacsjt6O8EDaawKJ-x4RWP46Xj-)
- [xxlarge](https://drive.google.com/drive/u/1/folders/1DlX_WZacsjt6O8EDaawKJ-x4RWP46Xj-)

**Comment by tejasvaidhyadev** [comment]
@aviks 
any suggestion on the roadmaps mentioned above.

**Comment by tejasvaidhyadev** [comment]
added Sentencepiece unigram support

**Comment by tejasvaidhyadev** [comment]
completed trainable Albert structure.

**Comment by tejasvaidhyadev** [comment]
fine-tuning Training Tutorial (it's not supported GPU so far)-
[here](https://github.com/tejasvaidhyadev/ALBERT.jl/blob/master/docs/TrainingTutorial.ipynb)

**Comment by tejasvaidhyadev** [comment]
not yet refractor 
code is pretty messy

**Comment by aviks** [comment]
Hi @tejasvaidhyadev can you move this PR to [TextModels](https://github.com/JuliaText/TextModels.jl) now please?

**Comment by tejasvaidhyadev** [comment]
> Hi @tejasvaidhyadev can you move this PR to [TextModels](https://github.com/JuliaText/TextModels.jl) now please?
Hi @aviks,
Is it okay, if I will do it the coming weekend?
I have exams this week

**Comment by aviks** [comment]
> I will do it the coming weekend?

Yes, of course, only whenever you have time.

**Pull request closed without merging**
