### PR TITLE
Update TextAnalysis.jl for supporting flux-zygote [WIP]

### PR DESCRIPTION
**Pull request by tejasvaidhyadev**
Addressing issue mention in #208

### CODE REVIEW

**Comment by tejasvaidhyadev** [comment]
Hi @Ayushk4 
Is it okay if I keep this PR on hold for now, as there is some work left in #180

**Comment by Ayushk4** [comment]
Okay. The work in #180 could take a while to be finished though, depending upon delay it takes for my system to be repaired.

**Comment by aviks** [comment]
It would be nice to get this going again.

**Comment by tejasvaidhyadev** [comment]
I will start actively contributing after 24 Dec.
I am rn busy with university examination

**Comment by aviks** [comment]
Overriden by https://github.com/JuliaText/TextModels.jl/pull/20

**Pull request closed without merging**
