### PR TITLE
Remove HTML style tags in preprocessing

### PR DESCRIPTION
**Pull request by phereford**
As we remove HTML tags in preprocessing, we should also be cognizant of any rogue `<style>` tags and remove those as needed as well.

Let me know if there is anything else I can add or change to get this merged in. Thank you for this wonderful library!

### CODE REVIEW

**Comment by Ayushk4** [comment]
Thank you so much for this phereford.

It will be great if you could add some tests to [test/preprocessing.jl](https://github.com/JuliaText/TextAnalysis.jl/blob/master/test/preprocessing.jl).

**Comment by aviks** [comment]
Thanks. Yes, some tests would be good, to ensure that we do not break this functionality in the future.

**Comment by phereford** [comment]
@aviks and @Ayushk4 thanks for the feedback! I will add unit tests now.

**Comment by phereford** [comment]
@aviks and @Ayushk4 I added a unit test styled like the other preprocessing unit tests. Let me know if there is anything else I can provide.

**Comment by aviks** [comment]
Thanks!

**Pull request merged**
