### PR TITLE
Change endof syntax

### PR DESCRIPTION
**Pull request by baggepinnen**

### CODE REVIEW

**Comment by aviks** [comment]
Hi, Could you rebase this on master?

**Comment by baggepinnen** [comment]
I submitted the PR to the branch `JuliaText:as/towards07` which was already ahead of master

**Comment by aviks** [comment]
Ah, OK, I didn't realise that. Thanks, that makes sense. 

 I'm actually hoping to get FemtoCleaner to post some fixes automatically  (it's having a hiccup currently)

**Comment by baggepinnen** [comment]
I have it setup locally, I could run it and submit to this branch if you'd like

**Comment by aviks** [comment]
Yeah, that would be great, thanks!

**Comment by baggepinnen** [comment]
Alright, that took me some head scratching getting the git magic in place, but now this PR contains changes from femtocleaner

**Pull request merged**
