### PR TITLE
Add extended example doc

### PR DESCRIPTION
**Pull request by aquatiko**
Adding Extended example doc. which was dropped while reorganising docs.

Closes: https://github.com/JuliaText/TextAnalysis.jl/issues/72

### CODE REVIEW

**Comment by aviks** [comment]
So `kmeans` is only in Clustering.jl, does not need MultiVariateStats. That package is required if we are doing a PCA or other dimensionality reduction techniques. I'm not sure what is sensible to do here. Thoughts?

**Comment by aquatiko** [comment]
@aviks  I'm not sure about the purpose of this section. Should this showcase the functions which are present in the package but not yet explained in docs or should they feature integration with other useful packages when someone is using this domain(like a gallery of useful implementations)?

**Comment by aviks** [comment]
The latter (gallery of useful implementations)

**Comment by aviks** [comment]
I'm merging this now, can fix it as we go along.

**Comment by aquatiko** [comment]
@aviks I would add more to this later. Should  I add an issue for this, so that it could be completed with more implementations later?

**Comment by aviks** [comment]
No issue necessary, just submit a PR when ready.

**Pull request merged**
