### PR TITLE
use getfield instead of eval in tagging_schemes.jl

### PR DESCRIPTION
**Pull request by rushabh-v**
resolves: https://github.com/JuliaText/TextAnalysis.jl/issues/242

On testing, it raises `UndefVarError: BIO1 not defined`. I tried figuring out the reason but couldn't. Should I use something else instead of `Main`?

I am new to Julia, please guide me.

### CODE REVIEW

**Comment by rushabh-v** [comment]
@aviks

**Comment by aviks** [comment]
You have to use the module in which these symbols are defined. Not `Main`. `Main` is the top level module (eg. in the REPL). These symbols are not defined in `Main`.

**Comment by rushabh-v** [comment]
they are defined in the same module (`tagging_schemes.jl`).

**Comment by rssdev10** [comment]
implemented in https://github.com/JuliaText/TextAnalysis.jl/pull/276/commits/57781294ab34136ee67eba0abb5e6c9b1a0fb733

**Pull request closed without merging**
