### PR TITLE
Latent Dirichlet allocation: display a progress bar during Gibbs sampling

### PR DESCRIPTION
**Pull request by DilumAluthge**
When running the `lda` function, the Gibbs sampling can take a long time if the corpus is very large. Without a progress bar, it can be hard to tell how much progress has been made, and how much time is remaining.

This pull request adds a progress bar that gets displayed during the Gibbs sampling.

To disable the progress bar, set the `showprogress` keyword argument to `false`, i.e.:
```julia
ϕ, θ = lda(dtm, ntopics, iterations, α, β; showprogress = false)
```

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Failures on nightly are #252

**Comment by DilumAluthge** [comment]
Bump @aviks

**Comment by DilumAluthge** [comment]
Thanks! Would it be possible to register a new release?

**Comment by aviks** [comment]
> Would it be possible to register a new release?

Yeah, once I manage to fix #252 ...

**Pull request merged**
