### PR TITLE
Fix Sequence Labelling Models, fixes #178

### LINKED ISSUE #178: Need to export Flux, Tracker
TextAnalysis now needs to export the `Flux` and `Tracker` symbols. That should not be required. 

Without those exports, loading the BSON models throws an error: 

```
 UndefVarError: Flux not defined
  Stacktrace:
   [1] (::BSON.var"#31#32")(::Module, ::String) at /home/aviks/.julia/packages/BSON/Ryxwc/src/extensions.jl:20
   [2] mapfoldl_impl(::typeof(identity), ::BSON.var"#31#32", ::NamedTuple{(:init,),Tuple{Module}}, ::Array{Any,1}) at ./reduce.jl:45
   [3] #mapfoldl#184(::Base.Iterators.Pairs{Symbol,Module,Tuple{Symbol},NamedTuple{(:init,),Tuple{Module}}}, ::typeof(mapfoldl), ::Function, ::Function, ::Array{Any,1}) at ./reduce.jl:72
   [4] #mapfoldl at ./none:0 [inlined]
   [5] _mapreduce_dim at ./reducedim.jl:310 [inlined]
   [6] #mapreduce#582 at ./reducedim.jl:307 [inlined]
   [7] #mapreduce at ./none:0 [inlined]
   [8] #reduce#584 at ./reducedim.jl:352 [inlined]
   [9] (::Base.var"#kw##reduce")(::NamedTuple{(:init,),Tuple{Module}}, ::typeof(reduce), ::Function, ::Array{Any,1}) at ./none:0
   [10] resolve(::Array{Any,1}) at /home/aviks/.julia/packages/BSON/Ryxwc/src/extensions.jl:20
   [11] (::BSON.var"#35#36")(::Dict{Symbol,Any}) at /home/aviks/.julia/packages/BSON/Ryxwc/src/extensions.jl:53
   [12] _raise_recursive(::Dict{Symbol,Any}, ::IdDict{Any,Any}) at /home/aviks/.julia/packages/BSON/Ryxwc/src/read.jl:79   [13] raise_recursive(::Dict{Symbol,Any}, ::IdDict{Any,Any}) at /home/aviks/.julia/packages/BSON/Ryxwc/src/read.jl:89    [14] (::BSON.var"#23#24"{IdDict{Any,Any}})(::Dict{Symbol,Any}) at /home/aviks/.julia/packages/BSON/Ryxwc/src/read.jl:94
   [15] applychildren!(::BSON.var"#23#24"{IdDict{Any,Any}}, ::Array{Any,1}) at /home/aviks/.julia/packages/BSON/Ryxwc/src/BSON.jl:28
   [16] raise_recursive at /home/aviks/.julia/packages/BSON/Ryxwc/src/read.jl:94 [inlined]
   [17] (::BSON.var"#19#21"{IdDict{Any,Any}})(::Array{Any,1}) at /home/aviks/.julia/packages/BSON/Ryxwc/src/read.jl:79     [18] applychildren!(::BSON.var"#19#21"{IdDict{Any,Any}}, ::Dict{Symbol,Any}) at /home/aviks/.julia/packages/BSON/Ryxwc/src/BSON.jl:21
   [19] _raise_recursive(::Dict{Symbol,Any}, ::IdDict{Any,Any}) at /home/aviks/.julia/packages/BSON/Ryxwc/src/read.jl:79   [20] raise_recursive(::Dict{Symbol,Any}, ::IdDict{Any,Any}) at /home/aviks/.julia/packages/BSON/Ryxwc/src/read.jl:89    [21] (::BSON.var"#45#46")(::Dict{Symbol,Any}, ::IdDict{Any,Any}) at /home/aviks/.julia/packages/BSON/Ryxwc/src/extensions.jl:138
   [22] raise_recursive(::Dict{Symbol,Any}, ::IdDict{Any,Any}) at /home/aviks/.julia/packages/BSON/Ryxwc/src/read.jl:88    [23] (::BSON.var"#20#22"{IdDict{Any,Any}})(::Dict{Symbol,Any}) at /home/aviks/.julia/packages/BSON/Ryxwc/src/read.jl:82
   [24] applychildren!(::BSON.var"#20#22"{IdDict{Any,Any}}, ::Dict{Symbol,Any}) at /home/aviks/.julia/packages/BSON/Ryxwc/src/BSON.jl:21
   [25] _raise_recursive(::Dict{Symbol,Any}, ::IdDict{Any,Any}) at /home/aviks/.julia/packages/BSON/Ryxwc/src/read.jl:82   [26] raise_recursive(::Dict{Symbol,Any}, ::IdDict{Any,Any}) at /home/aviks/.julia/packages/BSON/Ryxwc/src/read.jl:89    [27] raise_recursive at /home/aviks/.julia/packages/BSON/Ryxwc/src/read.jl:99 [inlined]
   [28] load at /home/aviks/.julia/packages/BSON/Ryxwc/src/read.jl:104 [inlined]
   [29] TextAnalysis.BiLSTM_CNN_CRF_Model(::Array{String,1}, ::Dict{Char,Int64}, ::Dict{String,Int64}, ::Int64, ::Int64, ::String) at /home/aviks/.julia/dev/TextAnalysis/src/sequence/sequence_models.jl:37
   [30] PoSTagger(::String, ::String) at /home/aviks/.julia/dev/TextAnalysis/src/sequence/pos.jl:14
   [31] PoSTagger() at /home/aviks/.julia/dev/TextAnalysis/src/sequence/pos.jl:10
   [32] top-level scope at /home/aviks/.julia/dev/TextAnalysis/test/pos.jl:4
```

### PR DESCRIPTION
**Pull request by Ayushk4**
The new weights file for NER is [here](https://github.com/Ayushk4/NER.jl/releases/download/0.0.0.1/ner_weights.tar.xz)

- NER
  - [X] 64-bit
  - [x] 32-bit
- POS
  - [X] 64-bit
  - [x] 32-bit

Addresses #178

### CODE REVIEW

**Comment by Ayushk4** [comment]
The weights modified weights for POS is [here](https://github.com/Ayushk4/POS.jl/releases/download/v0.0.1/pos_weights.tar.xz).

Ready for review. Travis tests pass for Julia 1.x

**Comment by aviks** [comment]
We don't want to support 0.7. Only 1.0 and 1.3

**Comment by Ayushk4** [comment]
So, should I send a separate PR updating travis and appveyor files?

**Comment by aviks** [comment]
Yup

**Comment by aviks** [comment]
@Ayushk4 you should be able to upload the weights to the release on this repo and update the source.

**Comment by Ayushk4** [comment]
@aviks Thanks, I will do that once all the tests pass.

**Comment by aviks** [comment]
Do you know why we've suddenly started to get these `NNPACKError(code 26, NNPACK STATUS UNSUPPORTED ALGORITHM)`? I know I had tests passing locally a few days ago, but now see these on my laptop as well. What has changed? Any ideas?

**Comment by Ayushk4** [comment]
I am not sure. After merging the changes from #181 to this patch, all the tests were passing (except for 32-bit appveyor). 

This is the first time I have come across `NNPACKError(code 26, NNPACK STATUS UNSUPPORTED ALGORITHM)` error. I am not sure what could be the reason for this.

**Comment by Ayushk4** [comment]
NNLib.jl recently had a patch release. I can try restricting the version to before that.

**Comment by aviks** [comment]
Yes, I was about to say, It's probably due to NNlib v0.6.1

**Comment by Ayushk4** [comment]
Even after changing Project.toml, Travis still installs NNlib 0.6.1 instead of the mentioned 0.6.0. Weird.

**Comment by aviks** [comment]
See discussion on slack `#pkg-usage` : 

```
[compat]
Flux = "< 0.10"
NNlib = "< 0.6.1"
julia = "1"
```

**Comment by Ayushk4** [comment]
That works! Travis tests pass now, only 32-bit appveyor left to deal with.

**Comment by Ayushk4** [comment]
Turns out that this is v0.6.1 is the first `NNlib` release since support for `NNPACK` pr got merged. I think  the error we were getting might have something to do with that, probably

**Comment by Ayushk4** [comment]
@aviks Is there any way to test Julia 32-bit on my 64-bit system? These tests solely fail on 32-bit on the bson files that were saved in a 64-bit system. I want to separate an MWE and report it and/or find a workaround.

**Comment by Ayushk4** [comment]
Here's more on the 32-bit issue with BSON.jl- JuliaIO/BSON.jl#60

**Comment by aviks** [comment]
That is great debugging. Very cool, @Ayushk4

**Comment by Ayushk4** [comment]
Thanks, I have filed a PR for the same. However, since it's holidays we could expect a delay in the review work. 
I believe that should fix the problems being faced in both the sequence and the sentiment models on 32-bit systems.

**Comment by Ayushk4** [comment]
Mike Innes has merged the PR. Is there anyways we can test the CI with the master branch of BSON.jl?

**Comment by aviks** [comment]
@Ayushk4 what is left on this one?

**Comment by Ayushk4** [comment]
I was waiting for JuliaIO/BSON.jl to have a new release with the fixes I made. I don't recall exactly what else is left. I will fix tomorrow.

**Comment by aviks** [comment]
@Ayushk4 Bump?

**Comment by Ayushk4** [comment]
I will look into it this Sunday.

**Comment by Ayushk4** [comment]
@aviks All models (NER, POS, sentiment and PerceptronTagger) work on 32-bit as well.
1 Test in ULMFiT seems to be failing in 1.3

**Comment by Ayushk4** [comment]
ULMFiT tests are passing locally for me on 1.3.1, updated Manifest.toml.

**Comment by Ayushk4** [comment]
@aviks Please review.

**Pull request merged**
