### PR TITLE
Update test infrastructure

### PR DESCRIPTION
**Pull request by baggepinnen**
Make use of `@test` and `@testset`

### CODE REVIEW

**Comment by laschuet** [comment]
I like it! Side note: There is one assert statement left in `metadata.jl` (L19).

**Comment by baggepinnen** [comment]
The last assert is removed now. This PR builds upon #86 and #89 , the whole chain is 
#86 -> #89 -> #91

**Comment by AsafManela** [comment]
PR seems to drop summarizer.jl, and sentiment.jl tests. Was that intentional?

**Comment by baggepinnen** [comment]
That was a mistake, should be corrected now!

**Pull request merged**
